version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      POSTGRES_DB: ai
    volumes: [ "./pgdata:/var/lib/postgresql/data" ]
  api:
    build: .
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      UNIFAI_AGENT_API_KEY: ${UNIFAI_AGENT_API_KEY}
      DB_URL: postgresql+psycopg2://ai:ai@db:5432/ai
    ports: [ "8000:8000" ]
    depends_on: [ db ]
